version: 2.1

general:
  branches:
    only:
      - master
      - stable

machine:
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${HOME}/${test}/node_modules/.bin:${PATH}"
  node:
    version: 16
  npm:
    version: 6

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/test
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: 'sudo npm install -g -force yarn'
      - run:
          name: Install Dependencies
          command: 'yarn install'
      - run:
          name: Run Compile and Test
          command: 'yarn run build && yarn test'